---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-feature-deploy-2
  namespace: argocd
spec:
  destination:
    namespace: realfullstack-feature
    server: 'https://kubernetes.default.svc'
  project: realfullstack
  source:
    path: kustomize-feature/overlays/feature-deploy-2
    repoURL: "https://github.com/realfullstack/frontend-infra.git"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
