apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: realfullstack-prod
nameSuffix: -prod
commonLabels:
  app-env: prod
configMapGenerator:
- behavior: merge
  envs:
  - files/config.env
  name: frontend
patches:
- path: patches/sealed-secret.yaml
  target:
    group: bitnami.com
    kind: SealedSecret
    name: frontend
    version: v1alpha1
images:
- name: frontend_main
  newName: ghcr.io/realfullstack/frontend/main_dev
  newTag: sha-a40d6c6
- name: frontend_nginx
  newName: ghcr.io/realfullstack/frontend/nginx
  newTag: sha-a40d6c6
resources:
- ../../base
