apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: realfullstack-feature
nameSuffix: -feature-deploy-2
commonLabels:
  app-env: feature
  # app.kubernetes.io/instance: frontend-feature-deploy-2
configMapGenerator:
- behavior: merge
  envs:
  - files/config.env
  name: frontend
patches:
- path: patches/sealed-secret.yaml
  target:
    group: bitnami.com
    kind: SealedSecret
    name: frontend
    version: v1alpha1
- patch: |-
    - op: replace
      path: /spec/tls/0/hosts
      value:
        - feature-deploy-2.feature.realfullstack.com
    - op: replace
      path: /spec/tls/0/secretName
      value: frontend-nginx-tls-key-feature-deploy-2
    - op: replace
      path: /spec/rules/0/host
      value: feature-deploy-2.feature.realfullstack.com
  target:
    group: networking.k8s.io
    kind: Ingress
    name: frontend-server-ingress
    version: v1
images:
- name: frontend_main
  newName: ghcr.io/realfullstack/frontend/main_dev
  newTag: sha-e88f9f9
- name: frontend_nginx
  newName: ghcr.io/realfullstack/frontend/nginx
  newTag: sha-e88f9f9
resources:
- ../../../kustomize/base
