apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend
configurations:
    - conf/namereference.yaml
    - conf/commonlabels.yaml
commonLabels:
  app: frontend
  app-project: realfullstack
resources:
  # wave 0
  - configmap.yaml
  - secret.yaml
  # wave 1
  - sealed-secret.yaml
  # wave 2 - migrations reserved
  # wave 3
  - deployment.yaml
  # wave 4
  - service.yaml
  - ingress.yaml