apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata: 
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
    argocd.argoproj.io/sync-wave: "1"
  name: frontend
spec:
  template: 
    metadata: 
      name: frontend
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        sealedsecrets.bitnami.com/managed: "true"
        argocd.argoproj.io/sync-wave: "0"
        argocd.argoproj.io/compare-options: IgnoreExtraneous
