apiVersion: v1
kind: Secret
metadata:
  name: frontend
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
    sealedsecrets.bitnami.com/managed: "true"
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
